#!/usr/bin/with-contenv bash

if ! dpkg -s vim >/dev/null 2>&1; then
    echo "**** Adding vim to package install list ****"
    echo "vim" >> /mod-repo-packages-to-install.list
    echo "build-essential" >> /mod-repo-packages-to-install.list
    echo "wget" >> /mod-repo-packages-to-install.list
    echo "iputils-ping" >> /mod-repo-packages-to-install.list
    echo "nmap" >> /mod-repo-packages-to-install.list
    echo "telnet" >> /mod-repo-packages-to-install.list
    echo "abc:10000:65536" >> /etc/subuid
    echo "abc:10000:65536" >> /etc/subgid
    echo "podman" >> /mod-repo-packages-to-install.list
    echo "uidmap" >> /mod-repo-packages-to-install.list
    echo "slirp4netns" >> /mod-repo-packages-to-install.list
else
    echo "**** vim already installed, skipping ****"
fi
